"""new beginning roof pro

Revision ID: 7c9344068f6f
Revises:
Create Date: 2025-06-04 22:07:48.360911

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7c9344068f6f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("inn", sa.String(), nullable=False),
        sa.Column("ogrn", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_company_id"), "company", ["id"], unique=False)
    op.create_index(op.f("ix_company_inn"), "company", ["inn"], unique=True)
    op.create_index(op.f("ix_company_ogrn"), "company", ["ogrn"], unique=True)
    op.create_table(
        "tariff",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("limit_users", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("price_sale", sa.Integer(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("atributes", sa.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tariff_id"), "tariff", ["id"], unique=False)
    op.create_table(
        "subscription",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "active", "inactive", "desktop", name="subscriptionstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expired_at", sa.DateTime(), nullable=True),
        sa.Column(
            "auto_renew", sa.Boolean(), server_default="f", nullable=False
        ),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("tariff_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"], ["company.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tariff_id"], ["tariff.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscription_company_id"),
        "subscription",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_id"), "subscription", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_subscription_tariff_id"),
        "subscription",
        ["tariff_id"],
        unique=False,
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fio", sa.String(), nullable=False),
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column(
            "is_email_verified",
            sa.Boolean(),
            server_default="f",
            nullable=False,
        ),
        sa.Column(
            "role",
            postgresql.ENUM("admin", "manager", name="userrole"),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default="f", nullable=False
        ),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"], ["company.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_company_id"), "user", ["company_id"], unique=False
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix_user_login"), "user", ["login"], unique=False)
    op.create_table(
        "session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("jwt_token", sa.String(), nullable=False),
        sa.Column(
            "device",
            postgresql.ENUM("mobile", "tablet", "desktop", name="devicetype"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("jwt_token"),
    )
    op.create_index(op.f("ix_session_id"), "session", ["id"], unique=False)
    op.create_index(
        op.f("ix_session_user_id"), "session", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_session_user_id"), table_name="session")
    op.drop_index(op.f("ix_session_id"), table_name="session")
    op.drop_table("session")
    op.drop_index(op.f("ix_user_login"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_index(op.f("ix_user_company_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_subscription_tariff_id"), table_name="subscription")
    op.drop_index(op.f("ix_subscription_id"), table_name="subscription")
    op.drop_index(
        op.f("ix_subscription_company_id"), table_name="subscription"
    )
    op.drop_table("subscription")
    op.drop_index(op.f("ix_tariff_id"), table_name="tariff")
    op.drop_table("tariff")
    op.drop_index(op.f("ix_company_ogrn"), table_name="company")
    op.drop_index(op.f("ix_company_inn"), table_name="company")
    op.drop_index(op.f("ix_company_id"), table_name="company")
    op.drop_table("company")
    # ### end Alembic commands ###
